Use MinVer and Microsoft.SourceLink.GitHub to generate assembly metadata at build time (#22)
This should remove the need for `Knapcode.NuGetTools.Build` altogether.

Also, running the `Knapcode.NuGetTools.Website` project after a fresh checkout just works, without any exception. Previously, it would throw `ArgumentNullException` because the `BuildTimestamp` assembly metadata would not be found.

> ArgumentNullException: String reference not set to an instance of a String. Parameter name: s
>   System.DateTimeParse.Parse(string s, DateTimeFormatInfo dtfi, DateTimeStyles styles, out TimeSpan offset)
>   System.DateTimeOffset.Parse(string input, IFormatProvider formatProvider, DateTimeStyles styles)
>   Knapcode.NuGetTools.Website.Configuration..cctor() in Configuration.cs